# 13.2 MovieLens 1M Dataset

## 1. Tải dữ liệu

In [16]:
import pandas as pd
unames = ["user_id", "gender", "age", "occupation", "zip"] # các cột cần lấy
users = pd.read_table("dataset/movielens/users.dat", sep="::", # lấy file và sep (separator) dùng phân tách cột bằng ký tự hoặc regex (biểu thức chính quy)
                      header=None, names=unames, engine="python") # parser để pandas đọc file
                                                                  # engine = c: Nhanh và chỉ hỗ trợ 1 ký tự
                                                                  # engine = python: Chậm nhưng hỗ trợ regex
                                                                  # engine = pyarrow: Rất nhan nhưng không hỗ trợ regex

rnames = ["user_id", "movie_id", "rating", "timestamp"]
ratings = pd.read_table("dataset/movielens/ratings.dat", sep="::",
                        header=None, names=rnames, engine="python")

mnames = ["movie_id", "title", "genres"]
movies = pd.read_table("dataset/movielens/movies.dat", sep="::",
                       header=None, names=mnames, engine="python")

display(users.head())
display(ratings.head())
display(movies.head())

   user_id gender  age  occupation    zip
0        1      F    1          10  48067
1        2      M   56          16  70072
2        3      M   25          15  55117
3        4      M   45           7  02460
4        5      M   25          20  55455

   user_id  movie_id  rating  timestamp
0        1      1193       5  978300760
1        1       661       3  978302109
2        1       914       3  978301968
3        1      3408       4  978300275
4        1      2355       5  978824291

   movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

**Nhận xét:**

Đây là 3 dữ liệu về dataset này trong đó:

<div align="center">
  <h3>Users</h3>
  <table style="border-collapse:collapse; margin:0 auto;">
    <tr>
      <th style="border:1px solid #ccc; padding:8px; text-align:center;">Tên cột</th>
      <th style="border:1px solid #ccc; padding:8px; text-align:center;">Ý nghĩa</th>
    </tr>
    <tr>
      <td style="border:1px solid #ccc; padding:8px; text-align:center;">user_id</td>
      <td style="border:1px solid #ccc; padding:8px; text-align:center;">Mã người dùng (khóa chính)</td>
    </tr>
    <tr>
      <td style="border:1px solid #ccc; padding:8px; text-align:center;">gender</td>
      <td style="border:1px solid #ccc; padding:8px; text-align:center;">Giới tính (M/F)</td>
    </tr>
    <tr>
      <td style="border:1px solid #ccc; padding:8px; text-align:center;">age</td>
      <td style="border:1px solid #ccc; padding:8px; text-align:center;">Tuổi (năm)</td>
    </tr>
    <tr>
      <td style="border:1px solid #ccc; padding:8px; text-align:center;">occupation</td>
      <td style="border:1px solid #ccc; padding:8px; text-align:center;">Mã nghề nghiệp (số; có bảng tra cứu)</td>
    </tr>
    <tr>
      <td style="border:1px solid #ccc; padding:8px; text-align:center;">zip</td>
      <td style="border:1px solid #ccc; padding:8px; text-align:center;">Mã bưu chính (chuỗi)</td>
    </tr>
  </table>
</div>

<div align="center">
  <h3>Ratings</h3>
  <table style="border-collapse:collapse; margin:0 auto;">
    <tr>
      <th style="border:1px solid #ccc; padding:8px; text-align:center;">Tên cột</th>
      <th style="border:1px solid #ccc; padding:8px; text-align:center;">Ý nghĩa</th>
    </tr>
    <tr>
      <td style="border:1px solid #ccc; padding:8px; text-align:center;">user_id</td>
      <td style="border:1px solid #ccc; padding:8px; text-align:center;">Khóa ngoại → users.user_id</td>
    </tr>
    <tr>
      <td style="border:1px solid #ccc; padding:8px; text-align:center;">movie_id</td>
      <td style="border:1px solid #ccc; padding:8px; text-align:center;">Khóa ngoại → movies.movie_id</td>
    </tr>
    <tr>
      <td style="border:1px solid #ccc; padding:8px; text-align:center;">rating</td>
      <td style="border:1px solid #ccc; padding:8px; text-align:center;">Điểm 1–5 (5 = thích nhất)</td>
    </tr>
    <tr>
      <td style="border:1px solid #ccc; padding:8px; text-align:center;">timestamp</td>
      <td style="border:1px solid #ccc; padding:8px; text-align:center;">Unix epoch (giây)</td>
    </tr>
  </table>
</div>

<div align="center">
  <h3>Movies</h3>
  <table style="border-collapse:collapse; margin:0 auto;">
    <tr>
      <th style="border:1px solid #ccc; padding:8px; text-align:center;">Tên cột</th>
      <th style="border:1px solid #ccc; padding:8px; text-align:center;">Ý nghĩa</th>
    </tr>
    <tr>
      <td style="border:1px solid #ccc; padding:8px; text-align:center;">movie_id</td>
      <td style="border:1px solid #ccc; padding:8px; text-align:center;">Mã phim (khóa chính)</td>
    </tr>
    <tr>
      <td style="border:1px solid #ccc; padding:8px; text-align:center;">title</td>
      <td style="border:1px solid #ccc; padding:8px; text-align:center;">Tiêu đề phim (thường kèm năm)</td>
    </tr>
    <tr>
      <td style="border:1px solid #ccc; padding:8px; text-align:center;">genres</td>
      <td style="border:1px solid #ccc; padding:8px; text-align:center;">Thể loại đa nhãn, nối bằng dấu “|”</td>
    </tr>
  </table>
</div>

## 2. Ghép Dữ liệu MovieLens

In [17]:
data = pd.merge(pd.merge(ratings, users), movies)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000209 entries, 0 to 1000208
Data columns (total 10 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   user_id     1000209 non-null  int64
 1   movie_id    1000209 non-null  int64
 2   rating      1000209 non-null  int64
 3   timestamp   1000209 non-null  int64
 4   gender      1000209 non-null  object
 5   age         1000209 non-null  int64
 6   occupation  1000209 non-null  int64
 7   zip         1000209 non-null  object
 8   title       1000209 non-null  object
 9   genres      1000209 non-null  object
dtypes: int64(6), object(4)
memory usage: 76.3+ MB

**Nhận xét:**
- Dữ liệu sau khi gộp 3 bảng, chứa 1.000.209 hàng và 10 cột, cho phép truy cập tất cả thông tin về user, rating, và movie trong cùng một hàng.
- Việc gộp dữ liệu làm dễ dàng hơn việc phân tích giữa các cột ở các bảng khác nhau một cách dễ dàng.

## 3. Phân tích khám phá

### 3.1 Tính điểm trung bình

In [18]:
mean_ratings = data.pivot_table("rating", index="title",
                                columns="gender", aggfunc="mean")
mean_ratings.head(5)

gender                                F         M
title
$1,000,000 Duck (1971)         3.375000  2.761905
'Night Mother (1986)           3.388889  3.352941
'Til There Was You (1997)      2.675676  2.733333
'burbs, The (1989)             2.793478  2.962085
...And Justice for All (1979)  3.828571  3.689024

**Nhận xét:**
- Trước hết có thể thấy rằng thứ tự xếp hạng trung bình (rating) cho mỗi tiêu đề phim (title) được nhóm theo giới tính (gender). 
- Dựa vào kết quả cho thấy nữ giới chiếm tỷ lệ xem cao hơn so với nam giới về các bộ phim.

### 3.2. Lọc phim phổ biến

In [19]:
ratings_by_title = data.groupby("title").size()
ratings_by_title.head()
active_titles = ratings_by_title.index[ratings_by_title >= 250]
active_titles

Index([''burbs, The (1989)', '10 Things I Hate About You (1999)',
       '101 Dalmatians (1961)', '101 Dalmatians (1996)', '12 Angry Men (1957)',
       '13th Warrior, The (1999)', '2 Days in the Valley (1996)',
       '20,000 Leagues Under the Sea (1954)', '2001: A Space Odyssey (1968)',
       '2010 (1984)',
       ...
       'X-Men (2000)', 'Year of Living Dangerously (1982)',
       'Yellow Submarine (1968)', 'You've Got Mail (1998)',
       'Young Frankenstein (1974)', 'Young Guns (1988)',
       'Young Guns II (1990)', 'Young Sherlock Holmes (1985)',
       'Zero Effect (1998)', 'eXistenZ (1999)'],
      dtype='object', name='title', length=1216)

In [20]:
mean_ratings = mean_ratings.loc[active_titles]
mean_ratings

gender                                    F         M
title
'burbs, The (1989)                 2.793478  2.962085
10 Things I Hate About You (1999)  3.646552  3.311966
101 Dalmatians (1961)              3.791444  3.500000
101 Dalmatians (1996)              3.240000  2.911215
12 Angry Men (1957)                4.184397  4.328421
...                                     ...       ...
Young Guns (1988)                  3.371795  3.425620
Young Guns II (1990)               2.934783  2.904025
Young Sherlock Holmes (1985)       3.514706  3.363344
Zero Effect (1998)                 3.864407  3.723140
eXistenZ (1999)                    3.098592  3.289086

[1216 rows x 2 columns]

**Nhận xét:**
- Thực hiện nhóm theo title và chỉ lấy số lượng phim ít nhất là 250 lượt xếp hạng.

Ví dụ, một bộ phim có 3 lượt xếp hạng (rating) và nhận được điểm trung bình là 5.0 sẽ không đáng tin cậy bằng một bộ phim có 250 lượt xếp hạng và điểm trung bình là 4.5. Việc đặt ngưỡng tối thiểu 250 đảm bảo rằng mỗi bộ phim được đưa vào phân tích tiếp theo (ví dụ: so sánh xếp hạng theo giới tính, tìm độ bất đồng) đều có một cơ sở dữ liệu đủ lớn.

**1) Độ lệch chuẩn (std) của các xếp hạng cho mỗi bộ phim**

In [21]:
mean_ratings["diff"] = mean_ratings["M"] - mean_ratings["F"]
sorted_by_diff = mean_ratings.sort_values("diff")
sorted_by_diff.head()
sorted_by_diff[::-1].head()
rating_std_by_title = data.groupby("title")["rating"].std()
rating_std_by_title = rating_std_by_title.loc[active_titles]
rating_std_by_title.head()

title
'burbs, The (1989)                   1.107760
10 Things I Hate About You (1999)    0.989815
101 Dalmatians (1961)                0.982103
101 Dalmatians (1996)                1.098717
12 Angry Men (1957)                  0.812731
Name: rating, dtype: float64

**Nhận xét:**
- Những tựa phim trên có mức phân cực ý kiến cao trong toàn bộ người xem (không riêng theo giới), phản ánh khác biệt về khẩu vị (ví dụ: hài tuổi teen, remake, phong cách cũ/đen-trắng,…).

- 'burbs, The (1989) đứng đầu → mức độ “hoặc thích hoặc ghét” rõ rệt nhất trong danh sách đang xét.

**2) “Liệu các thể loại phim cực đoan (kinh dị, tâm lý, chính trị) có xu hướng có độ lệch chuẩn rating cao hơn so với phim tình cảm, hài hay không?”.**

In [22]:
rating_std_by_title.sort_values(ascending=False)[:10]

title
Dumb & Dumber (1994)                     1.321333
Blair Witch Project, The (1999)          1.316368
Natural Born Killers (1994)              1.307198
Tank Girl (1995)                         1.277695
Rocky Horror Picture Show, The (1975)    1.260177
Eyes Wide Shut (1999)                    1.259624
Evita (1996)                             1.253631
Billy Madison (1995)                     1.249970
Fear and Loathing in Las Vegas (1998)    1.246408
Bicentennial Man (1999)                  1.245533
Name: rating, dtype: float64

**Nhận xét:**
- Có cơ sở cho thấy các thể loại “phân cực” (đặc biệt Horror/Kinh dị, Psychological/Arthouse như Eyes Wide Shut, Documentary, Cult/Experimental) có độ lệch chuẩn rating cao hơn so với các thể loại “an toàn” như Romance hay Comedy. Danh sách top phim lệch chuẩn cao bạn in ra gồm nhiều tác phẩm kinh dị/thử nghiệm/cult (Blair Witch Project, Rocky Horror, Fear and Loathing…)—đây là các phim thường “hoặc rất thích hoặc rất ghét”, nên phân tán điểm lớn.

## 4. Phân tích so sánh


**1) “Giữa các nhóm giới tính người dùng, phim nào có mức độ bất đồng ý kiến lớn nhất?”**

In [23]:
rating_std_by_title.sort_values(ascending=False)[:10]

title
Dumb & Dumber (1994)                     1.321333
Blair Witch Project, The (1999)          1.316368
Natural Born Killers (1994)              1.307198
Tank Girl (1995)                         1.277695
Rocky Horror Picture Show, The (1975)    1.260177
Eyes Wide Shut (1999)                    1.259624
Evita (1996)                             1.253631
Billy Madison (1995)                     1.249970
Fear and Loathing in Las Vegas (1998)    1.246408
Bicentennial Man (1999)                  1.245533
Name: rating, dtype: float64

**Nhận xét:**
- Nhóm phim đứng đầu gồm: Dumb & Dumber (1994), The Blair Witch Project (1999), Natural Born Killers (1994), Tank Girl (1995), The Rocky Horror Picture Show (1975), Eyes Wide Shut (1999), Evita (1996), Billy Madison (1995), Fear and Loathing in Las Vegas (1998), Bicentennial Man (1999).

Điểm chung nổi bật:

- Thể loại “phân cực”: hài “gây tranh cãi/nhảm” (Dumb & Dumber, Billy Madison), kinh dị/thử nghiệm (Blair Witch Project), bạo lực/tối màu (Natural Born Killers), phim văn hóa đối kháng/cult (Rocky Horror, Fear and Loathing), erotic-thriller (Eyes Wide Shut), nhạc kịch (Evita), hoặc bi kịch cảm xúc (Bicentennial Man).

>Các thể loại/thiết kế này thường tạo kỳ vọng khác nhau theo giới về nội dung, nhịp điệu và phong cách kể chuyện, do đó gây chênh lệch rõ rệt về mức yêu thích.

**2) “Người dùng trẻ tuổi (dưới 25) có xu hướng đánh giá cực đoan (1 hoặc 5) hơn so với nhóm lớn tuổi không?”**

In [24]:
movies["genres"].head()
movies["genres"].head().str.split("|")
movies["genre"] = movies.pop("genres").str.split("|")
movies.head()

,movie_id,title,genre
0,1,Toy Story (1995),"[Animation, Children's, Comedy]"
1,2,Jumanji (1995),"[Adventure, Children's, Fantasy]"
2,3,Grumpier Old Men (1995),"[Comedy, Romance]"
3,4,Waiting to Exhale (1995),"[Comedy, Drama]"
4,5,Father of the Bride Part II (1995),[Comedy]

In [25]:
movies_exploded = movies.explode("genre")
movies_exploded[:10]

   movie_id                     title       genre
0         1          Toy Story (1995)   Animation
0         1          Toy Story (1995)  Children's
0         1          Toy Story (1995)      Comedy
1         2            Jumanji (1995)   Adventure
1         2            Jumanji (1995)  Children's
1         2            Jumanji (1995)     Fantasy
2         3   Grumpier Old Men (1995)      Comedy
2         3   Grumpier Old Men (1995)     Romance
3         4  Waiting to Exhale (1995)      Comedy
3         4  Waiting to Exhale (1995)       Drama

**Nhận xét:**
- Sử dụng phương thức explode để biến đổi DataFrame: mỗi phần tử trong danh sách thể loại sẽ tạo ra một hàng riêng biệt với cùng thông tin phim.

In [26]:
ratings_with_genre = (
    movies_exploded.merge(ratings, on="movie_id")
                   .merge(users[["user_id","age"]], on="user_id")
)
age_to_bin = {
    1:  "1-18",     
    18: "18-25",   
    25: "25-35",  
    35: "35-45",  
    45: "45-56",   
    50: "45-56",   
    56: "45-56",
}
ratings_with_genre["age_bin"] = ratings_with_genre["age"].map(age_to_bin)

keep_bins = ["1-18", "18-25", "25-35", "35-45", "45-56"]
ratings_with_genre = ratings_with_genre[ratings_with_genre["age_bin"].isin(keep_bins)]
# mean
genre_ratings = (
    ratings_with_genre.groupby(["genre", "age_bin"])["rating"].mean().unstack("age_bin").reindex(columns=keep_bins)
)

# Xem 10 dòng đầu
genre_ratings.head(10)

age_bin          1-18     18-25     25-35     35-45     45-56
genre
Action       3.506385  3.447097  3.453358  3.538107  3.575216
Adventure    3.449975  3.408525  3.443163  3.515291  3.588214
Animation    3.476113  3.624014  3.701228  3.740545  3.753997
Children's   3.241642  3.294257  3.426873  3.518423  3.553587
Comedy       3.497491  3.460417  3.490385  3.561984  3.623254
Crime        3.710170  3.668054  3.680321  3.733736  3.790194
Documentary  3.730769  3.865865  3.946690  3.953747  3.944075
Drama        3.794735  3.721930  3.726428  3.782512  3.852067
Fantasy      3.317647  3.353778  3.452484  3.482301  3.550607
Film-Noir    4.145455  3.997368  4.058725  4.064910  4.136925

**Nhận xét:**
- Hầu hết các thể loại (Action, Adventure, Animation, Children’s, Comedy, Crime, Documentary, Drama, Fantasy, Film-Noir) đều có xu hướng điểm trung bình tăng theo tuổi: các cột 1–18 và 18–25 thấp hơn rõ so với 35–45 và 45–56 (mức chênh ~0.1–0.3 điểm tùy thể loại).

>Kết luận trực tiếp từ bảng này: người dùng trẻ (<25) không cho thấy xu hướng “cực đoan” hay “hào phóng”; họ đơn giản là khắt khe hơn (điểm trung bình thấp hơn) so với nhóm lớn tuổi.

# KẾT THÚC